#%RAML 1.0
title: Sample API
baseUri: http://localhost:8081/api

/log:
  get:
    description: Basic Logger Test
    responses: 
      200:
        body: 
          application/json:
/elapsedTimers:
  get:
    description: |
      Advanced Inner Timers. Allows independent calculation of elapsed 
      times for sub-processes by using a dynamic timer flowVar
    responses:
      200:
        body:
          application/json: 